### ISSUE TITLE
How to calculate BERT Next Sentence Prediction Score

### ISSUE THREAD

**Issue by liuwei1206** [tanyuqian/progressive-generation#4]
Hello,

Thanks for your excellent work. 

I noticed that you use the next sentence prediction score to evaluate text coherence.  Can you share with me the detail of how to do it?  Did you calculate it using only two successive sentences?  or the whole left and right context text?

For example, a document has five sentences "A B C D E", when calculating the score between 2nd and 3rd sentences, you calculate it using:
method 1: input [CLS] B [SEP] C [SEP] into BERT, or
method 2: input [CLS] A B [SEP] C D E [SEP] into BERT ?
I hope you can share with me the detail of how to input sentences into BERT.

Thanks!

**Comment by tanyuqian** [comment]
Thanks for reading our paper!

We make use of the BERT NSP pretrain task without any finetuning, and we calculate this score using only two successive sentences. For example, in our paper Fig. 1, if a document has five sentences "A B C D E", the numbers of ```x=4``` will be calculated by BERT input ```D [SEP] E```.
